DEFAULT_ALIASES = {
    "德国": "Germany",
    "德國": "Germany",
    "germany": "Germany",
    "usa": "United States",
    "u.s.a.": "United States",
    "united states": "United States",
    "美国": "United States",
    "美國": "United States",
    "south korea": "Korea Republic",
    "korea republic": "Korea Republic",
    "韩国": "Korea Republic",
    "韓國": "Korea Republic",
    "england": "England",
    "英格兰": "England",
    "france": "France",
    "法国": "France",
    "spain": "Spain",
    "西班牙": "Spain",
    "italy": "Italy",
    "意大利": "Italy",
    "brazil": "Brazil",
    "巴西": "Brazil",
    "argentina": "Argentina",
    "阿根廷": "Argentina",
    "japan": "Japan",
    "日本": "Japan",
    "china": "China PR",
    "china pr": "China PR",
    "中国": "China PR",
    "中國": "China PR",
}
