DEFAULT_ALIASES = {
    "德国": "Germany",
    "德國": "Germany",
    "germany": "Germany",
    "west germany": "Germany",
    "frg": "Germany",
    "east germany": "Germany",
    "usa": "United States",
    "u.s.a.": "United States",
    "united states": "United States",
    "united states of america": "United States",
    "美国": "United States",
    "美國": "United States",
    "south korea": "Korea Republic",
    "korea republic": "Korea Republic",
    "韩国": "Korea Republic",
    "韓國": "Korea Republic",
    "england": "England",
    "英格兰": "England",
    "france": "France",
    "法国": "France",
    "法國": "France",
    "spain": "Spain",
    "西班牙": "Spain",
    "italy": "Italy",
    "意大利": "Italy",
    "brazil": "Brazil",
    "巴西": "Brazil",
    "argentina": "Argentina",
    "阿根廷": "Argentina",
    "japan": "Japan",
    "日本": "Japan",
    "china": "China PR",
    "china pr": "China PR",
    "中国": "China PR",
    "中國": "China PR",
    "netherlands": "Netherlands",
    "holland": "Netherlands",
    "荷兰": "Netherlands",
    "荷蘭": "Netherlands",
    "portugal": "Portugal",
    "葡萄牙": "Portugal",
    "czech republic": "Czech Republic",
    "czechia": "Czech Republic",
    "捷克": "Czech Republic",
    "russia": "Russia",
    "俄罗斯": "Russia",
    "俄羅斯": "Russia",
    "soviet union": "Russia",
    "yugoslavia": "Serbia",
    "serbia": "Serbia",
    "塞尔维亚": "Serbia",
    "塞爾維亞": "Serbia",
}
